version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/Docker/api'
    schedule:
      interval: 'monthly'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - 'P-manBrown'
    commit-message:
      prefix: 'build'
    target-branch: 'main'
  - package-ecosystem: 'docker'
    directory: '/Docker/db'
    schedule:
      interval: 'monthly'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - 'P-manBrown'
    ignore:
      - dependency-name: 'mysql'
        versions: ['>=8.5']
    commit-message:
      prefix: 'build'
    target-branch: 'main'
  - package-ecosystem: 'docker'
    directory: '/Docker/web'
    schedule:
      interval: 'monthly'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: 'build'
    target-branch: 'main'
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '03:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - 'P-manBrown'
    commit-message:
      prefix: 'build'
    target-branch: 'main'
