commits:
  author:
    capitalization:
      enabled: false
    email:
      enabled: false
    name:
      enabled: false
  body:
    bullet:
      enabled: false
    bullet_capitalization:
      enabled: false
    bullet_delimiter:
      enabled: false
    tracker_shorthand:
      enabled: false
    leading_line:
      enabled: true
      severity: error
    line_length:
      enabled: true
      severity: error
      maximum: 72
    paragraph_capitalization:
      enabled: true
      severity: error
    phrase:
      enabled: false
    presence:
      enabled: false
    single_bullet:
      enabled: false
  signature:
    enabled: false
  subject:
    length:
      enabled: true
      severity: error
      maximum: 72
    prefix:
      enabled: true
      severity: error
      delimiter: "!?: "
      includes:
        - build
        - chore
        - ci
        - docs
        - feat
        - fix
        - format
        - improve
        - revert
        - test
    suffix:
      enabled: true
      severity: error
      excludes:
        - "\\."
  trailer:
    collaborator_capitalization:
      enabled: false
    collaborator_email:
      enabled: false
    collaborator_key:
      enabled: false
    collaborator_name:
      enabled: false
    duplicate:
      enabled: false
    format_key:
      enabled: false
    format_value:
      enabled: false
    issue_key:
      enabled: false
    issue_value:
      enabled: false
    signer_capitalization:
      enabled: false
    signer_email:
      enabled: false
    signer_key:
      enabled: false
    signer_name:
      enabled: false
    tracker_key:
      enabled: false
    tracker_value:
      enabled: false
