require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-erb
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - "bin/{bundle,rails,rake}"
    - "db/migrate/*"
    - "db/schema.rb"
    - "vendor/**/*"

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "config/**/*"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
