name: Task
description: Use this template for creating tasks related to project development.
title: "<type>[!]: <subject>"
labels: ["task"]
assignees:
  - P-manBrown
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the task. What needs to be done? Why is this task necessary?
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the requirements that must be met for the task to be considered completed.
      value: |
        - [ ]
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Include any additional information, links, or references that may be relevant to completing the task.
    validations:
      required: false
