services:
  api:
    volumes:
      - shell-log:/home/${API_USER_NAME}/shell_log
    command: bash -c 'while sleep 1000; do :; done'
    env_file:
      - ./.devcontainer/environment/gh-token.env
volumes:
  shell-log:
  vscode-global-storage:
